name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build_android:
    runs-on: ubuntu-20.04
    name: Build for Android

    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Download Gradle
      run: |
        wget -q https://downloads.gradle-dn.com/distributions/gradle-6.2.2-bin.zip
        unzip gradle-6.2.2-bin.zip

    - name: Download NDK
      run: |
        wget -q https://dl.google.com/android/repository/android-ndk-r20-linux-x86_64.zip
        unzip android-ndk-r20-linux-x86_64.zip
        mv android-ndk-r20 android-ndk

    - name: Clone
      run: |
        git clone https://github.com/openvinotoolkit/openvino_contrib --depth 1
        git clone https://github.com/openvinotoolkit/openvino -b releases/2022/2
        cd openvino && git submodule init && git submodule update --recursive

    - name: Install Java
      uses: actions/setup-java@v1
      with:
        java-version: '11.0.2'

    - name: Build OpenVINO
      run: |
        mkdir openvino_build && cd openvino_build

        cmake \
          -DANDROID_ABI=arm64-v8a \
          -DANDROID_PLATFORM=21 \
          -DANDROID_STL=c++_shared \
          -DENABLE_INTEL_MYRIAD=OFF \
          -DENABLE_CLDNN=OFF \
          -DENABLE_OPENCV=OFF \
          -DENABLE_TEMPLATE=OFF \
          -DENABLE_SAMPLES=OFF \
          -DTHREADING=SEQ \
          -DBUILD_nvidia_plugin=OFF \
          -DIE_EXTRA_MODULES=$HOME/openvino_contrib/modules \
          -DCMAKE_TOOLCHAIN_FILE=$HOME/android-ndk/build/cmake/android.toolchain.cmake $HOME/openvino

        make --jobs=$(nproc --all)
        cmake --install . --prefix $HOME/openvino_install

    - name: Build package
      run: |
        source $HOME/openvino_install/setupvars.sh
        cp $HOME/settings.gradle $HOME/build.gradle .
        gradle clean build --info
      working-directory: openvino_contrib/modules/java_api
