name: CI

on:
  push:
    branches: [ main ]
  pull_request:

env:
  OPENVINO_BRANCH: 2021.2
  BASE_VERSION: 2021.2.4

jobs:
  # run_linux:
  #   runs-on: ubuntu-18.04
  #   name: Build on Linux

  #   steps:
  #   - name: Clone repository
  #     uses: actions/checkout@v2

  #   - name: Clone OpenVINO
  #     run: |
  #       git clone -b ${{env.OPENVINO_BRANCH}} https://github.com/openvinotoolkit/openvino
  #       git clone -b mo_pytorch_manifest https://github.com/dkurt/openvino_contrib

  #   - name: Install dependencies
  #     run: |
  #       sudo apt-get update
  #       sudo apt-get install -y default-jdk libusb-1.0-0-dev

  #   - name: Build
  #     run: |
  #       cd openvino
  #       git submodule init
  #       git submodule update --recursive

  #       mkdir build && cd build
  #       cmake .. \
  #         -DCMAKE_BUILD_TYPE=Release \
  #         -DIE_EXTRA_MODULES=../../openvino_contrib/modules \
  #         -DBUILD_arm_plugin=OFF \
  #         -DENABLE_CLDNN=OFF \
  #         -DENABLE_VPU=OFF \
  #         -DENABLE_GNA=OFF \
  #         -DENABLE_SAMPLES=OFF \
  #         -DENABLE_OPENCV=OFF \
  #         -DENABLE_CPPLINT=OFF \
  #         -DENABLE_PYTHON=OFF
  #       make -j$(nproc --all)

  #   - name: Publish
  #     env:
  #       BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
  #       BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
  #       VERSION: "${{env.BASE_VERSION}}-linux-x86_64"
  #     run: |
  #       cd openvino_contrib/modules/java_api
  #       mkdir native
  #       mv ../../../openvino/bin/intel64/Release/lib/*.so native
  #       mv ../../../openvino/inference-engine/temp/tbb/lib/libtbb.so.2 native
  #       mv ../../../openvino/bin/intel64/Release/lib/plugins.xml native
  #       gradle bintrayUpload

  run_win:
    runs-on: windows-latest
    name: Build on Windows

    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Clone OpenVINO
      run: |
        git clone -b ${{env.OPENVINO_BRANCH}} https://github.com/openvinotoolkit/openvino
        git clone -b mo_pytorch_manifest https://github.com/dkurt/openvino_contrib

    - name: Install Java
      uses: actions/setup-java@v1
      with:
        java-version: '11.0.2'

    - name: Build
      run: |
        cd openvino
        git submodule init
        git submodule update --recursive

        mkdir build && cd build
        cmake .. ^
          -G "Visual Studio 16 2019" -A x64 ^
          -DCMAKE_BUILD_TYPE=Release ^
          -DIE_EXTRA_MODULES=..\..\openvino_contrib\modules ^
          -DBUILD_arm_plugin=OFF ^
          -DENABLE_MKL_DNN=OFF ^
          -DENABLE_CLDNN=OFF ^
          -DENABLE_VPU=OFF ^
          -DENABLE_GNA=OFF ^
          -DENABLE_SAMPLES=OFF ^
          -DENABLE_OPENCV=OFF ^
          -DENABLE_CPPLINT=OFF ^
          -DENABLE_PYTHON=OFF
        cmake --build . --config Release -j 2
      shell: cmd

    # - name: Publish
    #   env:
    #     BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
    #     BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
    #     VERSION: "${{env.BASE_VERSION}}-windows-x86_64"
    #   run: |
    #     cd openvino_contrib/modules/java_api
    #     mkdir native
    #     mv ../../../openvino/bin/intel64/Release/lib/*.so native
    #     mv ../../../openvino/inference-engine/temp/tbb/lib/libtbb.so.2 native
    #     mv ../../../openvino/bin/intel64/Release/lib/plugins.xml native
    #     gradle bintrayUpload
